//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHLGames.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHLGames.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Add Entry.
        /// </summary>
        public static string btnAddHosts {
            get {
                return ResourceManager.GetString("btnAddHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Remove Entries.
        /// </summary>
        public static string btnCleanHosts {
            get {
                return ResourceManager.GetString("btnCleanHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string btnClearConsole {
            get {
                return ResourceManager.GetString("btnClearConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string btnCopyConsole {
            get {
                return ResourceManager.GetString("btnCopyConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) View Hosts.
        /// </summary>
        public static string btnOpenHostsFile {
            get {
                return ResourceManager.GetString("btnOpenHostsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Test.
        /// </summary>
        public static string btnTestHosts {
            get {
                return ResourceManager.GetString("btnTestHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Scores.
        /// </summary>
        public static string chkShowFinalScores {
            get {
                return ResourceManager.GetString("chkShowFinalScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Scores.
        /// </summary>
        public static string chkShowLiveScores {
            get {
                return ResourceManager.GetString("chkShowLiveScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Record.
        /// </summary>
        public static string chkShowSeriesRecord {
            get {
                return ResourceManager.GetString("chkShowSeriesRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending.
        /// </summary>
        public static string enumending {
            get {
                return ResourceManager.GetString("enumending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string enumfinal {
            get {
                return ResourceManager.GetString("enumfinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string enuminprogress {
            get {
                return ResourceManager.GetString("enuminprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregame.
        /// </summary>
        public static string enumpregame {
            get {
                return ResourceManager.GetString("enumpregame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string enumscheduled {
            get {
                return ResourceManager.GetString("enumscheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [cli].
        /// </summary>
        public static string errorCliStreamlink {
            get {
                return ResourceManager.GetString("errorCliStreamlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t find NHLGames config file. You will have to reinstall NHLGames..
        /// </summary>
        public static string errorConfigFile {
            get {
                return ResourceManager.GetString("errorConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Failed to deserialize setting value of &apos;{0}&apos; to type &apos;{1}&apos;.
        /// </summary>
        public static string errorDeserialize {
            get {
                return ResourceManager.GetString("errorDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error:.
        /// </summary>
        public static string errorDetection {
            get {
                return ResourceManager.GetString("errorDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string errorDoubleDot {
            get {
                return ResourceManager.GetString("errorDoubleDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception.
        /// </summary>
        public static string errorExceptionDetection {
            get {
                return ResourceManager.GetString("errorExceptionDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Failed to fetch games schedule..
        /// </summary>
        public static string errorFetchingGames {
            get {
                return ResourceManager.GetString("errorFetchingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string errorGeneral {
            get {
                return ResourceManager.GetString("errorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t find mpv.exe : mpv is a media player that we shipped with NHLGames. You probably moved it or deleted it. Please set a player, NHLGames needs one..
        /// </summary>
        public static string errorMpvExe {
            get {
                return ResourceManager.GetString("errorMpvExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No media player selected in settings..
        /// </summary>
        public static string errorPlayerPathEmpty {
            get {
                return ResourceManager.GetString("errorPlayerPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Failed to read app setting: {0}.
        /// </summary>
        public static string errorReadingSettings {
            get {
                return ResourceManager.GetString("errorReadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t set Ad Detection Modules. Verify if a Nugget package has a dependency of an older nugget package that you have installed (ex: Spotify and Json): {0}.
        /// </summary>
        public static string errorSetAdModule {
            get {
                return ResourceManager.GetString("errorSetAdModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:  Can&apos;t find streamlink.exe. Streamlink is a tool that NHLGames uses to send streams to your media player, we shipped it with NHLGames. You probably moved it or deleted it and if you don&apos;t set any custom path, you will have to put it back there, just drop the folder &apos;streamlink-0.8.1&apos; next to NHLGames.exe..
        /// </summary>
        public static string errorStreamlinkExe {
            get {
                return ResourceManager.GetString("errorStreamlinkExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unable to decode url from NHL API, the structure has changed. We will have to fix this..
        /// </summary>
        public static string errorUnableToDecodeJson {
            get {
                return ResourceManager.GetString("errorUnableToDecodeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown (server is not available).
        /// </summary>
        public static string errorUnknownServerDown {
            get {
                return ResourceManager.GetString("errorUnknownServerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Failed to write app settings.
        /// </summary>
        public static string errorWritingSettings {
            get {
                return ResourceManager.GetString("errorWritingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB/Hour.
        /// </summary>
        public static string formatGbHour {
            get {
                return ResourceManager.GetString("formatGbHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB/Hour.
        /// </summary>
        public static string formatMbHour {
            get {
                return ResourceManager.GetString("formatMbHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} {2}, {3}.
        /// </summary>
        public static string formatWeekMonthDayYear {
            get {
                return ResourceManager.GetString("formatWeekMonthDayYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st.
        /// </summary>
        public static string gamePeriod1 {
            get {
                return ResourceManager.GetString("gamePeriod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd.
        /// </summary>
        public static string gamePeriod2 {
            get {
                return ResourceManager.GetString("gamePeriod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd.
        /// </summary>
        public static string gamePeriod3 {
            get {
                return ResourceManager.GetString("gamePeriod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string gamePeriodFinal {
            get {
                return ResourceManager.GetString("gamePeriodFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT.
        /// </summary>
        public static string gamePeriodOt {
            get {
                return ResourceManager.GetString("gamePeriodOt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}OT.
        /// </summary>
        public static string gamePeriodOtMore {
            get {
                return ResourceManager.GetString("gamePeriodOtMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leads.
        /// </summary>
        public static string gameSeriesLead {
            get {
                return ResourceManager.GetString("gameSeriesLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tied.
        /// </summary>
        public static string gameSeriesTied {
            get {
                return ResourceManager.GetString("gameSeriesTied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins.
        /// </summary>
        public static string gameSeriesWin {
            get {
                return ResourceManager.GetString("gameSeriesWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Team : {0} {1}.
        /// </summary>
        public static string lblAwayTeam {
            get {
                return ResourceManager.GetString("lblAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} camera views.
        /// </summary>
        public static string lblCamViews {
            get {
                return ResourceManager.GetString("lblCamViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDN.
        /// </summary>
        public static string lblCdn {
            get {
                return ResourceManager.GetString("lblCdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} endzone camera.
        /// </summary>
        public static string lblEndzoneCam {
            get {
                return ResourceManager.GetString("lblEndzoneCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string lblFrench {
            get {
                return ResourceManager.GetString("lblFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Canadian stream.
        /// </summary>
        public static string lblFrenchNetwork {
            get {
                return ResourceManager.GetString("lblFrenchNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game {0}.
        /// </summary>
        public static string lblGame {
            get {
                return ResourceManager.GetString("lblGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM {0}: {1}.
        /// </summary>
        public static string lblGameAbv {
            get {
                return ResourceManager.GetString("lblGameAbv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download MPC.
        /// </summary>
        public static string lblGetMpc {
            get {
                return ResourceManager.GetString("lblGetMpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download VLC.
        /// </summary>
        public static string lblGetVlc {
            get {
                return ResourceManager.GetString("lblGetVlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team : {0} {1}.
        /// </summary>
        public static string lblHomeTeam {
            get {
                return ResourceManager.GetString("lblHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server&apos;s Hostname.
        /// </summary>
        public static string lblHostname {
            get {
                return ResourceManager.GetString("lblHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Hosts Entry.
        /// </summary>
        public static string lblHosts {
            get {
                return ResourceManager.GetString("lblHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPC Path.
        /// </summary>
        public static string lblMpcPath {
            get {
                return ResourceManager.GetString("lblMpcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPV Path.
        /// </summary>
        public static string lblMpvPath {
            get {
                return ResourceManager.GetString("lblMpvPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National stream.
        /// </summary>
        public static string lblNationalNetwork {
            get {
                return ResourceManager.GetString("lblNationalNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game found.
        /// </summary>
        public static string lblNoGames {
            get {
                return ResourceManager.GetString("lblNoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stream available.
        /// </summary>
        public static string lblNoStreamAvailable {
            get {
                return ResourceManager.GetString("lblNoStreamAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Refreshing games is required for CDN change to take effect.
        /// </summary>
        public static string lblNoteCdn {
            get {
                return ResourceManager.GetString("lblNoteCdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on {0}.
        /// </summary>
        public static string lblOnNetwork {
            get {
                return ResourceManager.GetString("lblOnNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string lblOutput {
            get {
                return ResourceManager.GetString("lblOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Player.
        /// </summary>
        public static string lblPlayer {
            get {
                return ResourceManager.GetString("lblPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Args.
        /// </summary>
        public static string lblPlayerArgs {
            get {
                return ResourceManager.GetString("lblPlayerArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playoffs.
        /// </summary>
        public static string lblPlayoffs {
            get {
                return ResourceManager.GetString("lblPlayoffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preseason.
        /// </summary>
        public static string lblPreseason {
            get {
                return ResourceManager.GetString("lblPreseason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Quality.
        /// </summary>
        public static string lblQuality {
            get {
                return ResourceManager.GetString("lblQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee camera.
        /// </summary>
        public static string lblRefCam {
            get {
                return ResourceManager.GetString("lblRefCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scores.
        /// </summary>
        public static string lblShowScores {
            get {
                return ResourceManager.GetString("lblShowScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamlink Path.
        /// </summary>
        public static string lblSlPath {
            get {
                return ResourceManager.GetString("lblSlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streams available during pregame.
        /// </summary>
        public static string lblStreamAvailableDuringPregame {
            get {
                return ResourceManager.GetString("lblStreamAvailableDuringPregame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer Args.
        /// </summary>
        public static string lblStreamerArgs {
            get {
                return ResourceManager.GetString("lblStreamerArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stream.
        /// </summary>
        public static string lblTeamStream {
            get {
                return ResourceManager.GetString("lblTeamStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC Path.
        /// </summary>
        public static string lblVlcPath {
            get {
                return ResourceManager.GetString("lblVlcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string lnkCalendarToday {
            get {
                return ResourceManager.GetString("lnkCalendarToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add our server to your hosts file.
        /// </summary>
        public static string msgAddHost {
            get {
                return ResourceManager.GetString("msgAddHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} file is now set back to Read Only.
        /// </summary>
        public static string msgAddReadOnly {
            get {
                return ResourceManager.GetString("msgAddReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts: Backing up file: {0}.
        /// </summary>
        public static string msgBackingHostsFile {
            get {
                return ResourceManager.GetString("msgBackingHostsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available! Changes: {1}{2}{3}.
        /// </summary>
        public static string msgChangeLog {
            get {
                return ResourceManager.GetString("msgChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts: Removing existing entries from hosts file.
        /// </summary>
        public static string msgCleanHostsFile {
            get {
                return ResourceManager.GetString("msgCleanHostsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] .
        /// </summary>
        public static string msgDateTimeNow {
            get {
                return ResourceManager.GetString("msgDateTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string msgDiySteps {
            get {
                return ResourceManager.GetString("msgDiySteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This line needs to be insert in your hosts file : {0}{1} {2}{0}Click on &apos;Open Hosts File&apos; to open the Hosts file and paste (Ctrl+V) that entry line at the end of your Hosts file.{0}Do you want to copy that entry line to your clipboard ?.
        /// </summary>
        public static string msgDiyStepsText {
            get {
                return ResourceManager.GetString("msgDiyStepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading: Game schedule for {0} to {1}.
        /// </summary>
        public static string msgDownloadingJsonFile {
            get {
                return ResourceManager.GetString("msgDownloadingJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened! See the console for more details.{0}Click on [?] button in the top-right corner to view NHLGames documentation for quick support in the Support section (App and Player).{0}You can also copy the console log using &apos;Copy to clipboard&apos; button and paste it in a new thread on NHLGames subreddit for help. Use the link in the bottom-left corner to get there..
        /// </summary>
        public static string msgErrorGeneralText {
            get {
                return ResourceManager.GetString("msgErrorGeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string msgFailure {
            get {
                return ResourceManager.GetString("msgFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching.
        /// </summary>
        public static string msgFetching {
            get {
                return ResourceManager.GetString("msgFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching: Saved game schedule for {0} ({1}).
        /// </summary>
        public static string msgFetchingSavedSchedule {
            get {
                return ResourceManager.GetString("msgFetchingSavedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Found : {0}.
        /// </summary>
        public static string msgGamesFound {
            get {
                return ResourceManager.GetString("msgGamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Game schedule for {1} from NHL.tv.
        /// </summary>
        public static string msgGettingSchedule {
            get {
                return ResourceManager.GetString("msgGettingSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHLGames can&apos;t work without having its hostname set in your Windows Hosts file. Do you want to let NHLGames adds an entry to your Hosts file, so Windows can resolve NHLGames hostname and connect to its server&apos;s IP address?.
        /// </summary>
        public static string msgHostnameSet {
            get {
                return ResourceManager.GetString("msgHostnameSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts entry doesn&apos;t seem to be working :(.
        /// </summary>
        public static string msgHostsFailure {
            get {
                return ResourceManager.GetString("msgHostsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts file looks good!.
        /// </summary>
        public static string msgHostsSuccess {
            get {
                return ResourceManager.GetString("msgHostsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Games.
        /// </summary>
        public static string msgLoadingGames {
            get {
                return ResourceManager.GetString("msgLoadingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        public static string msgNewVersionAvailable {
            get {
                return ResourceManager.GetString("msgNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available, download the latest version {0} on /r/nhl_games.
        /// </summary>
        public static string msgNewVersionText {
            get {
                return ResourceManager.GetString("msgNewVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string msgOff {
            get {
                return ResourceManager.GetString("msgOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string msgOn {
            get {
                return ResourceManager.GetString("msgOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing.
        /// </summary>
        public static string msgRefreshing {
            get {
                return ResourceManager.GetString("msgRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove our server from your hosts file.
        /// </summary>
        public static string msgRemoveHost {
            get {
                return ResourceManager.GetString("msgRemoveHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: The {0} file is no longer Read Only.
        /// </summary>
        public static string msgRemoveReadOnly {
            get {
                return ResourceManager.GetString("msgRemoveReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Access Required.
        /// </summary>
        public static string msgRunAsAdmin {
            get {
                return ResourceManager.GetString("msgRunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHLGames is missing the required hosts file entry. Do you want to restart this application as an Administrator and add the required entry?.
        /// </summary>
        public static string msgRunAsAdminText {
            get {
                return ResourceManager.GetString("msgRunAsAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Failed to download the game schedule file from {0}. Second attempt..
        /// </summary>
        public static string msgServerNoRespondTryingAgain {
            get {
                return ResourceManager.GetString("msgServerNoRespondTryingAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Server {0} seems down.
        /// </summary>
        public static string msgServerSeemsDown {
            get {
                return ResourceManager.GetString("msgServerSeemsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Setting updated for &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        public static string msgSettingUpdated {
            get {
                return ResourceManager.GetString("msgSettingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting: {0} {1}.
        /// </summary>
        public static string msgStartingApp {
            get {
                return ResourceManager.GetString("msgStartingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vs {1}.
        /// </summary>
        public static string msgTeamVsTeam {
            get {
                return ResourceManager.GetString("msgTeamVsTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test the hosts file.
        /// </summary>
        public static string msgTestHosts {
            get {
                return ResourceManager.GetString("msgTestHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test ability to write to this directory.
        /// </summary>
        public static string msgTestTxtContent {
            get {
                return ResourceManager.GetString("msgTestTxtContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enable.
        /// </summary>
        public static string msgThisEnable {
            get {
                return ResourceManager.GetString("msgThisEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Value too large for display].
        /// </summary>
        public static string msgValueTooLarge {
            get {
                return ResourceManager.GetString("msgValueTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hosts File.
        /// </summary>
        public static string msgViewHosts {
            get {
                return ResourceManager.GetString("msgViewHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to view the changes NHLGames made to your Hosts file?.
        /// </summary>
        public static string msgViewHostsText {
            get {
                return ResourceManager.GetString("msgViewHostsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video On Demand Status: {0}.
        /// </summary>
        public static string msgVOD {
            get {
                return ResourceManager.GetString("msgVOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string tabConsole {
            get {
                return ResourceManager.GetString("tabConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string tabGames {
            get {
                return ResourceManager.GetString("tabGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string tabModules {
            get {
                return ResourceManager.GetString("tabModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHLGames Official Bug Report {1}{0}{0}OS : {2} {3}{0}{0}UI loaded : {4}{0}{0}Domain resolved : {5}{0}{0}Server IP found : {6}{0}{0}Selected hostname : {7}{0}{0}Selected player : {8}{0}{0}Streamlink path : {9} [=UI:{10}]{0}{0}VLC path : {11} [=UI:{12}]{0}{0}MPC path : {13} [=UI:{14}]{0}{0}MPV path : {15} [=UI:{16}]{0}{0}Console log : {0}{0}{17}.
        /// </summary>
        public static string textCopyConsole {
            get {
                return ResourceManager.GetString("textCopyConsole", resourceCulture);
            }
        }
    }
}
